require(ascii)
require(plyr)
require(reshape)
require(ggplot2)
options(width = 150)

## source("R/correlation.r")
## source("R/freq.r")
## source("R/funs.r")
## source("R/layout.r")
## source("R/na.r")
## source("R/parse.r")
## source("R/rbind.r")
## source("R/remix.r")
## source("R/summarize.by.r")
## source("R/summarize.r")
## source("R/table.r")
## source("R/tabular.r")
## source("R/plot.r")
for (i in list.files("R", full.names = TRUE)) source(i)
